# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-byte-order-marker

  # CPP hooks
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        args: [--style=Google]
  # The same options as in ament_cppcheck are used, but its not working...
  #- repo: https://github.com/pocc/pre-commit-hooks
    #rev: v1.1.1
    #hooks:
      #- id: cppcheck
        #args: ['--error-exitcode=1', '-f', '--inline-suppr', '-q', '-rp', '--suppress=internalAstError', '--suppress=unknownMacro', '--verbose']

  #- repo: local
    #hooks:
      #- id: ament_cppcheck
        #name: ament_cppcheck
        #description: Static code analysis of C/C++ files.
        #stages: [commit]
        #entry: ament_cppcheck
        #language: system
        #files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$

  ## Maybe use https://github.com/cpplint/cpplint instead
  #- repo: local
    #hooks:
      #- id: ament_cpplint
        #name: ament_cpplint
        #description: Static code analysis of C/C++ files.
        #stages: [commit]
        #entry: ament_cpplint
        #language: system
        #files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
        #args: ["--linelength=100", "--filter=-whitespace/newline"]

  ## Cmake hooks
  #- repo: local
    #hooks:
      #- id: ament_lint_cmake
        #name: ament_lint_cmake
        #description: Check format of CMakeLists.txt files.
        #stages: [commit]
        #entry: ament_lint_cmake
        #language: system
        #files: CMakeLists\.txt$

  ## Copyright
  #- repo: local
    #hooks:
      #- id: ament_copyright
        #name: ament_copyright
        #description: Check if copyright notice is available in all files.
        #stages: [commit]
        #entry: ament_copyright
        #language: system

  # Spellcheck in comments and docs
  # skipping of *.svg files is not working...
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args: ['--write-changes']
        exclude: \.(svg|pyc)$
